apiVersion: apps/v1
kind: Deployment
metadata:
  name: server2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
      - name: server2
        image: your-dockerhub-username/flask-server-1:latest
        ports:
        - containerPort: 5002


---

apiVersion: v1
kind: Service
metadata:
  name: server2-service
spec:
  selector:
    app: server2
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
  type: NodePort



